// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LoginMenu: typeof import('./src/components/LoginMenu.vue')['default']
    NetworkSubsetter: typeof import('./src/components/NetworkSubsetter.vue')['default']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VOverlay: typeof import('vuetify/lib')['VOverlay']
    VRow: typeof import('vuetify/lib')['VRow']
    VSlider: typeof import('vuetify/lib')['VSlider']
  }
}
