// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LoginMenu: typeof import('./src/components/LoginMenu.vue')['default']
    NetworkSubsetter: typeof import('./src/components/NetworkSubsetter.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VAppBarTitle: typeof import('vuetify/lib')['VAppBarTitle']
    VAutocomplete: typeof import('vuetify/lib')['VAutocomplete']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VList: typeof import('vuetify/lib')['VList']
    VListItem: typeof import('vuetify/lib')['VListItem']
    VListItemAction: typeof import('vuetify/lib')['VListItemAction']
    VListItemTitle: typeof import('vuetify/lib')['VListItemTitle']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VOverlay: typeof import('vuetify/lib')['VOverlay']
    VRow: typeof import('vuetify/lib')['VRow']
    VSlider: typeof import('vuetify/lib')['VSlider']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarItems: typeof import('vuetify/lib')['VToolbarItems']
    VToolbarNavIcon: typeof import('vuetify/lib')['VToolbarNavIcon']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
    VTooltip: typeof import('vuetify/lib')['VTooltip']
  }
}
